typography_spectrum: 0.07053900393657386
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8796886317431927
  lightness: 0.4935800787061453
  saturation: 0.3604336343705654
  rhythmicContrast: 0.23585370578803122
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.5589263481087983
analytics:
  google: null
  facebook: null
  twitter: null
name: Marlo's Massage
cta:
  domain: null
  bucket: null
  version: null
favicon: null
description: Dream Solutions
purpose: []
